# Generated by Django 5.0.2 on 2024-02-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
