# Generated by Django 5.0.2 on 2024-02-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_api', '0002_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nr',
            field=models.IntegerField(unique=True),
        ),
    ]
